name = "bsprvse"
version = "1.0.0"
license = "MIT"
author = "Viatcheslav Kokoouline"
maintainer = "j.forer@posteo.net"
description = "Solves the molecular (ro)vibrational 1D Schrödinger equation, optionally with a complex absorbing potential"
keywords = [ "Schrödinger", "equation", "complex", "absorbing", "potential", "bound", "states" ]

[build]
module-naming = true
link = ["lapack"]

[library]
source-dir = "src"

# [dev-dependencies]
# test-drive.git = "https://github.com/fortran-lang/test-drive"
# test-drive.tag = "v0.4.0"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
main="main.f"
source-dir="main"
name="bsprvse"

[[test]]
name="test"
source-dir="test"
main="test.f"
